language: node_js
node_js:
  - 10.9
install:
  - npm install
script:
  - npm run lint

after_success:
#  - ./services orion
#  - export TEST_ENDPOINT=http://localhost:1026
#  - npm test

- ./services scorpio
- export TEST_ENDPOINT=http://localhost:9090
- npm test