language: node_js
node_js:
  - 12.14
env:
  - STAGE=compliance
  - STAGE=orion
  - STAGE=scorpio
  - STAGE=stellio

services:
  - docker

matrix:
  allow_failures:
  - env: STAGE=orion
  - env: STAGE=scorpio
  - env: STAGE=stellio

install: >
  npm install;
  if [[ "${STAGE}" == "orion" ]]; then
     docker-compose --log-level ERROR -f docker-compose/orion.yml pull --ignore-pull-failures 
  fi
  
  if [[ "${STAGE}" == "scorpio" ]]; then
    docker-compose --log-level ERROR -f docker-compose/scorpio-aaio.yml pull --ignore-pull-failures 
    docker-compose --log-level ERROR -f docker-compose/scorpio-dist.yml pull --ignore-pull-failures 
  fi

  if [[ "${STAGE}" == "stellio" ]]; then
     docker-compose --log-level ERROR -f docker-compose/stellio.yml pull --ignore-pull-failures 
  fi
  
before_script: >
  if [[ "${STAGE}" == "orion" ]]; then
     ./services orion;
     export TEST_ENDPOINT=http://localhost:1026;
  fi
  
  if [[ "${STAGE}" == "scorpio" ]]; then
     ./services scorpio;
     export TEST_ENDPOINT=http://localhost:9090;
  fi

  if [[ "${STAGE}" == "stellio" ]]; then
     ./services stellio;
     export TEST_ENDPOINT=http://localhost:8080;
  fi

script: >
  if [[ "${STAGE}" == "compliance" ]]; then
     npm run lint;
  else
     npm test;
  fi
