version: "3.5"

services:

  accumulator:
    image: fiware/accumulator
    hostname: accumulator
    container_name: accumulator
    build:
      context: ../accumulator
      dockerfile: Dockerfile
    expose: 
      - "${ACC_PORT}"
    ports:
      - "${ACC_PORT}:${ACC_PORT}" # localhost:3000
    environment:
      - WEB_APP_PORT=${ACC_PORT}

  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - default
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    container_name: kafka
    networks:
      - default
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
      
  postgres:
    image: mdillon/postgis
    hostname: postgres
    container_name: db-postgres
    networks:
      - default
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb

  scorpio:
    image: scorpiobroker/scorpio:scorpio-aaio_${SCORPIO_VERSION}
    hostname: scorpio
    container_name: fiware-scorpio
    networks:
      - default
    ports:
      - "${SCORPIO_PORT}:9090"
    depends_on:
      - kafka
      - postgres
    healthcheck:
      test: curl --fail -s http://scorpio:${SCORPIO_PORT}/scorpio/v1/info/ || exit 1

networks:
  default: ~