name: Orion Test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  test-orion:
    name: Test Suite against Orion-LD
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Set-up Orion
        run: |
          export $(cat .env | grep "#" -v)
          docker-compose -f docker-compose/orion.yml -p fiware up -d
          docker ps
          echo -e "Waiting for 20 seconds ..."
          sleep 20
          docker ps
      - name: Run Test Suite Against Orion
        run: |
          export TEST_ENDPOINT=http://localhost:1026;
          npm install
          npm test
