name: Orion Test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-orion:
    name: Test Suite against Orion-LD
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Test Suite Against Orion
        run: |
          docker-compose --log-level ERROR -f docker-compose/orion.yml pull --ignore-pull-failures
          docker-compose --log-level ERROR -f docker-compose/orion.yml -p fiware up -d --remove-orphans
          ./services orion;
          export TEST_ENDPOINT=http://localhost:1026;
          npm install
          npm test