name: Stellio Test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-stellio:
    name: Test Suite against Stellio Broker
    runs-on: ubuntu-latest
    continue-on-error: true
    timeout-minutes: 5
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Run Test Suite Against Stellio
        run: |
          docker-compose --log-level ERROR -f docker-compose/stellio.yml pull --ignore-pull-failures 
          ./services stellio;
          docker ps
          export TEST_ENDPOINT=http://localhost:8080;
          npm install
          npm test